[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = "1.45.1"
tokio-util = { version = "0.7.15", features = ["io"] }
argon2 = "0.5.3"
getrandom = { version = "0.2", features = ["js"] }
aes-gcm = "0.10.3"
serde = { version = "1.0.219", features = ["derive"] }
